### ISSUE TITLE
Array out of bounds move right (Shape Y)

### ISSUE THREAD

**Issue by hkstm** [Takowski/pentris#15]
![riqhl3h](https://user-images.githubusercontent.com/13365775/33313512-2880b36a-d42b-11e7-8901-99cc3ca8549a.png)
![luqv979](https://user-images.githubusercontent.com/13365775/33313533-3f18691a-d42b-11e7-9cda-38028f5e6cbf.png)
![iefpu2c](https://user-images.githubusercontent.com/13365775/33313537-41354024-d42b-11e7-894c-35e0ec11a585.png)

**Comment by hkstm** [comment]
Also the case for shapes I and U, not T.

**Comment by thebot002** [comment]
fixed
